apiVersion: v1
kind: Service
metadata:
  name: legends-tournaments-frontend-service
  namespace: tournament
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
    name: http
  selector:
    app: legends-tournaments-frontend