---
micronaut:
  application:
    name: api
  server:
    cors:
      enabled: true
#      configurations:
#        web:
#          allowedOrigins:
#            - http://localhost:8088
#          allowedMethods:
#            - POST
#            - PUT
#            - GET
---
tournament:
  datastore:
    projectid: legends-tournaments
    namespace: testing
  security:
    endpoints:
      username: ${SECRET_USERNAME:unused}
      password: ${SECRET_PASSWORD:unused}
