apiVersion: v1
kind: Namespace
metadata:
  name: tournament
---
apiVersion: v1
kind: Service
metadata:
  namespace: tournament
  name: web
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80
    name: http
  selector:
    app: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tournament
  name: web
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: markjfisher/legends-tournaments-frontend
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80